// Feedback collection (IndexedDB, own database): paragraphs for which the user says where
// the text really comes from - basis for eval sets, calibration and own fine-tuning.
//
// Unlike the score store it contains the TEXT (otherwise it is useless as training data) - therefore
// only after explicit consent (storage.local `feedbackConsentAt`, see content.js), local only,
// no URL, never sent automatically. Export as JSONL in the settings.
//
// Exactly one entry per text (key = hash over the text): new feedback replaces the old one.
//   id     128-bit SHA-256 over the text
//   text   exactly the text the model scored (up to 2000 characters)
//   label  "human" | "ai" - the person's answer
//   basis  "own" (written/generated by oneself, author known) | "date" (published before 2023) |
//          "marked" (labeled as AI) | "guess" (just an impression - no reliable label)
//   p, model  score and AIVSAI.modelKey at the time of the feedback
//   lang   <html lang> of the page, source "auto" | "manual" | "selection", at (ms), v (schema version)

const DB_NAME = "aivsai-feedback";
const STORE = "feedback";
const SCHEMA = 1;
const MAX_ENTRIES = 20_000; // ~40 MB at 2000 characters - far more than anyone collects by hand

export const LABELS = ["human", "ai"];
export const BASES = ["own", "date", "marked", "guess"];

let dbPromise = null;

function openDb() {
  dbPromise ||= new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);
    req.onupgradeneeded = () => req.result.createObjectStore(STORE, { keyPath: "id" });
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  }).catch((err) => {
    dbPromise = null;
    throw err;
  });
  return dbPromise;
}

const done = (req) =>
  new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });

const committed = (tx) =>
  new Promise((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onerror = tx.onabort = () => reject(tx.error);
  });

async function idFor(text) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(digest, 0, 16), (b) => b.toString(16).padStart(2, "0")).join("");
}

/** Validates and normalizes an entry from the content script - the page can interfere there. */
function sanitize(e) {
  const text = typeof e?.text === "string" ? e.text.trim().slice(0, 2000) : "";
  if (!text) throw new Error("No text");
  if (!LABELS.includes(e.label)) throw new Error(`Unknown label: ${e.label}`);
  if (!BASES.includes(e.basis)) throw new Error(`Unknown basis: ${e.basis}`);
  return {
    text,
    label: e.label,
    basis: e.basis,
    p: typeof e.p === "number" && e.p >= 0 && e.p <= 1 ? e.p : null,
    model: String(e.model ?? "").slice(0, 200),
    lang: String(e.lang ?? "").slice(0, 20),
    source: ["auto", "manual", "selection"].includes(e.source) ? e.source : "manual"
  };
}

/** @returns {Promise<string>} id of the stored entry (for "Undo") */
export async function put(entry) {
  const clean = sanitize(entry);
  const id = await idFor(clean.text);
  const db = await openDb();
  if ((await done(db.transaction(STORE).objectStore(STORE).count())) >= MAX_ENTRIES) {
    throw new Error(`Collection full (${MAX_ENTRIES.toLocaleString("en-US")} entries) – please export and delete.`);
  }
  const tx = db.transaction(STORE, "readwrite");
  tx.objectStore(STORE).put({ id, ...clean, at: Date.now(), v: SCHEMA });
  await committed(tx);
  return id;
}

/** Stored answer for exactly this text or null - so the popover can show and change it. */
export async function get(text) {
  const clean = typeof text === "string" ? text.trim().slice(0, 2000) : "";
  if (!clean) return null;
  const row = await done((await openDb()).transaction(STORE).objectStore(STORE).get(await idFor(clean)));
  return row ?? null;
}

export async function remove(id) {
  const tx = (await openDb()).transaction(STORE, "readwrite");
  tx.objectStore(STORE).delete(String(id));
  await committed(tx);
}

export async function all() {
  const rows = await done((await openDb()).transaction(STORE).objectStore(STORE).getAll());
  return rows.sort((a, b) => a.at - b.at);
}

export async function info() {
  const rows = await all();
  const count = (fn) => rows.filter(fn).length;
  return {
    count: rows.length,
    human: count((r) => r.label === "human"),
    ai: count((r) => r.label === "ai"),
    guess: count((r) => r.basis === "guess"),
    // Model was wrong: human but >= 50% or AI but < 50%
    disagree: count((r) => r.p !== null && (r.label === "ai") !== r.p >= 0.5),
    bytes: rows.reduce((n, r) => n + r.text.length * 2 + 200, 0)
  };
}

export async function clear() {
  const tx = (await openDb()).transaction(STORE, "readwrite");
  tx.objectStore(STORE).clear();
  await committed(tx);
}
