const DEFAULTS = {
  enabled: true,
  threshold: 0.90,
  serverUrl: "http://127.0.0.1:8787", // shim_server.py, not laya-serve directly
  model: "tmr" // "tmr" | "english" | "multilingual" - see server/shim_server.py
};

async function getConfig() {
  const stored = await chrome.storage.sync.get(DEFAULTS);
  return { ...DEFAULTS, ...stored };
}

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg?.type !== "SCORE_BATCH") return false;
  scoreBatch(msg.items, sender)
    .then(sendResponse)
    .catch((err) => sendResponse({ ok: false, error: String(err) }));
  return true; // keep the message channel open for the async response
});

async function scoreBatch(items, sender) {
  const config = await getConfig();
  if (!config.enabled || !items?.length) return { ok: true, scores: {} };

  const hostname = (() => {
    try {
      return sender.tab?.url ? new URL(sender.tab.url).hostname : "";
    } catch {
      return "";
    }
  })();

  const state = {
    hostname,
    candidates: items.map((it) => ({ text: it.text }))
  };

  const questions = {};
  items.forEach((_, i) => {
    questions[`c${i}`] = {
      type: "noul",
      instructions:
        `Is candidates[${i}].text primarily generated by an AI/LLM, rather than written ` +
        `by a human? Judge only the writing style/patterns, not the topic or correctness.`
    };
  });

  // fail open: any network/HTTP error just means "no scores this round",
  // never blocks or breaks the page.
  const resp = await fetch(`${config.serverUrl}/v1/systemone`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ model: config.model, state, questions })
  });
  if (!resp.ok) throw new Error(`laya-serve HTTP ${resp.status}`);

  const data = await resp.json();
  const scores = {};
  items.forEach((it, i) => {
    const ans = data.answers?.[`c${i}`];
    if (ans && typeof ans.noul === "number") scores[it.id] = ans.noul;
  });
  return { ok: true, scores };
}
