// Builds the weights file for the desklib model from the original (model.safetensors, fp32) according to the
// build recipe models/desklib/recipe.json (generated by scripts/build_desklib_skeleton.py).
// The 1.7 GB are read as a stream and quantized row by row - the whole original is never
// in memory, only the result (~475 MB).

// numpy/ORT round half values to the even number, Math.round always rounds up
function roundHalfEven(x) {
  const r = Math.round(x);
  return Math.abs(x % 1) === 0.5 && r % 2 !== 0 ? r - 1 : r;
}

// MatMulNBits, 8-bit symmetric (like onnxruntime.quantization): per block scale = value with the largest
// magnitude / -128, stored as uint8 with zero point 128.
function quantizeNbits8Row(row, n, t, out, block) {
  const cols = row.length;
  const blocks = cols / block;
  const q = out.subarray(t.q + n * cols, t.q + (n + 1) * cols);
  const scales = new Float32Array(out.buffer, out.byteOffset + t.scales + n * blocks * 4, blocks);
  for (let b = 0; b < blocks; b++) {
    let max = 0;
    let maxAbs = 0;
    for (let j = b * block; j < (b + 1) * block; j++) {
      const a = Math.abs(row[j]);
      if (a > maxAbs) {
        maxAbs = a;
        max = row[j];
      }
    }
    const scale = Math.fround(max / -128);
    scales[b] = scale;
    for (let j = b * block; j < (b + 1) * block; j++) {
      const v = scale === 0 ? 0 : roundHalfEven(Math.fround(row[j] / scale));
      q[j] = Math.min(255, Math.max(0, v + 128));
    }
  }
}

// Word embeddings: int8 with one scale per row (value with the largest magnitude / 127)
function quantizeEmbRow(row, n, t, out) {
  const cols = row.length;
  let maxAbs = 0;
  for (let j = 0; j < cols; j++) maxAbs = Math.max(maxAbs, Math.abs(row[j]));
  const scale = maxAbs === 0 ? 1 : Math.fround(maxAbs / 127);
  new Float32Array(out.buffer, out.byteOffset + t.scales + n * 4, 1)[0] = scale;
  const q = new Int8Array(out.buffer, out.byteOffset + t.q + n * cols, cols);
  for (let j = 0; j < cols; j++) q[j] = Math.min(127, Math.max(-127, roundHalfEven(Math.fround(row[j] / scale))));
}

// Reads exactly n bytes in sequence from a ReadableStream reader
class ByteReader {
  constructor(reader, onBytes) {
    this.reader = reader;
    this.onBytes = onBytes;
    this.chunk = new Uint8Array(0);
    this.pos = 0;
  }

  async next() {
    const { done, value } = await this.reader.read();
    if (done) throw new Error("Download ended prematurely");
    this.chunk = value;
    this.pos = 0;
    this.onBytes(value.byteLength);
  }

  // calls sink(part) for consecutive pieces until n bytes have been read
  async read(n, sink) {
    while (n > 0) {
      if (this.pos >= this.chunk.byteLength) await this.next();
      const take = Math.min(n, this.chunk.byteLength - this.pos);
      sink(this.chunk.subarray(this.pos, this.pos + take));
      this.pos += take;
      n -= take;
    }
  }

  async readAll(n) {
    const buf = new Uint8Array(n);
    let off = 0;
    await this.read(n, (part) => {
      buf.set(part, off);
      off += part.byteLength;
    });
    return buf;
  }
}

/**
 * @param {ReadableStream<Uint8Array>} stream  contents of model.safetensors
 * @param {object} recipe  recipe.json
 * @param {(loaded: number) => void} onProgress  total bytes read
 * @returns {Promise<Uint8Array>} contents of the .onnx_data file
 */
export async function buildWeights(stream, recipe, onProgress = () => {}) {
  let loaded = 0;
  const bytes = new ByteReader(stream.getReader(), (n) => onProgress((loaded += n)));
  const headerLen = Number(new DataView((await bytes.readAll(8)).buffer).getBigUint64(0, true));
  const header = JSON.parse(new TextDecoder().decode(await bytes.readAll(headerLen)));
  delete header.__metadata__;

  const out = new Uint8Array(recipe.dataSize);
  const tensors = Object.entries(header).sort((a, b) => a[1].data_offsets[0] - b[1].data_offsets[0]);
  const missing = Object.keys(recipe.tensors).filter((k) => !header[k]);
  if (missing.length) throw new Error(`Original file does not match the build recipe (missing: ${missing[0]})`);

  let pos = 0; // position in the data area
  for (const [name, info] of tensors) {
    const [begin, end] = info.data_offsets;
    await bytes.read(begin - pos, () => {}); // skip gap (normally there is none)
    const size = end - begin;
    const t = recipe.tensors[name];
    if (!t) {
      await bytes.read(size, () => {});
    } else if (info.dtype !== "F32") {
      throw new Error(`${name}: data type ${info.dtype} instead of F32`);
    } else if (t.kind === "copy") {
      let off = 0;
      await bytes.read(size, (part) => {
        for (const target of t.targets) out.set(part, target + off);
        off += part.byteLength;
      });
    } else {
      // row by row: collect a row (pieces can end in the middle of a number), then quantize
      const rowBytes = t.cols * 4;
      const rowBuf = new Uint8Array(rowBytes);
      const row = new Float32Array(rowBuf.buffer);
      let fill = 0;
      let n = 0;
      await bytes.read(size, (part) => {
        let p = 0;
        while (p < part.byteLength) {
          const take = Math.min(rowBytes - fill, part.byteLength - p);
          rowBuf.set(part.subarray(p, p + take), fill);
          fill += take;
          p += take;
          if (fill === rowBytes) {
            if (t.kind === "nbits8") quantizeNbits8Row(row, n, t, out, recipe.block);
            else quantizeEmbRow(row, n, t, out);
            n++;
            fill = 0;
          }
        }
      });
      if (n !== t.rows) throw new Error(`${name}: ${n} instead of ${t.rows} rows`);
    }
    pos = end;
  }
  return out;
}
