"""
Evaluiert ein oder mehrere Backends gegen eval_sample.jsonl (100 balancierte
Beispiele aus dem HC3-Holdout-Split) und druckt Accuracy@0.5 + AUROC.

Nutzung:
    .venv/Scripts/python.exe evaluate_backends.py --backend laya
    .venv/Scripts/python.exe evaluate_backends.py --backend tmr
"""

import argparse
import json

import requests


def load_sample(path="eval_sample.jsonl"):
    rows = [json.loads(l) for l in open(path, encoding="utf-8")]
    return [(r["text"], r["label"]) for r in rows]


def auroc(labels, scores):
    pairs = sorted(zip(scores, labels))
    n_pos = sum(labels)
    n_neg = len(labels) - n_pos
    if n_pos == 0 or n_neg == 0:
        return float("nan")
    rank_sum = 0.0
    i = 0
    n = len(pairs)
    while i < n:
        j = i
        while j < n and pairs[j][0] == pairs[i][0]:
            j += 1
        avg_rank = (i + 1 + j) / 2.0
        for k in range(i, j):
            if pairs[k][1] == 1:
                rank_sum += avg_rank
        i = j
    return (rank_sum - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)


def acc_at(labels, scores, thresh):
    preds = [1 if s >= thresh else 0 for s in scores]
    return sum(p == l for p, l in zip(preds, labels)) / len(labels), preds


def report(name, labels, scores):
    acc50, preds50 = acc_at(labels, scores, 0.5)
    a = auroc(labels, scores)

    best_t, best_acc = 0.5, acc50
    for i in range(1, 100):
        t = i / 100
        acc, _ = acc_at(labels, scores, t)
        if acc > best_acc:
            best_acc, best_t = acc, t

    tp = sum(p == 1 and l == 1 for p, l in zip(preds50, labels))
    fp = sum(p == 1 and l == 0 for p, l in zip(preds50, labels))
    fn = sum(p == 0 and l == 1 for p, l in zip(preds50, labels))
    tn = sum(p == 0 and l == 0 for p, l in zip(preds50, labels))

    _, preds_best = acc_at(labels, scores, best_t)
    tp2 = sum(p == 1 and l == 1 for p, l in zip(preds_best, labels))
    fp2 = sum(p == 1 and l == 0 for p, l in zip(preds_best, labels))
    fn2 = sum(p == 0 and l == 1 for p, l in zip(preds_best, labels))
    tn2 = sum(p == 0 and l == 0 for p, l in zip(preds_best, labels))

    print(f"\n=== {name} ===")
    print(f"Accuracy@0.5: {acc50:.3f}   AUROC: {a:.3f}")
    print(f"Confusion@0.5: TP={tp} FP={fp} FN={fn} TN={tn}")
    print(f"Score-Range: min={min(scores):.3f} max={max(scores):.3f} mean={sum(scores)/len(scores):.3f}")
    print(f"Beste Schwelle auf diesem Sample: {best_t:.2f} -> Accuracy={best_acc:.3f}")
    print(f"Confusion@best: TP={tp2} FP={fp2} FN={fn2} TN={tn2}")

    with open(f"eval_scores_{name}.jsonl", "w", encoding="utf-8") as f:
        for s, l in zip(scores, labels):
            f.write(json.dumps({"score": s, "label": l}) + "\n")


def score_laya(texts, server_url="http://127.0.0.1:11500", model="english"):
    scores = []
    batch_size = 8
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        state = {"candidates": [{"text": t} for t in batch]}
        questions = {
            f"c{j}": {
                "type": "noul",
                "instructions": (
                    f"Is candidates[{j}].text primarily generated by an AI/LLM, rather than "
                    "written by a human? Judge only the writing style/patterns, not the topic or correctness."
                ),
            }
            for j in range(len(batch))
        }
        resp = requests.post(
            f"{server_url}/v1/systemone",
            json={"model": model, "state": state, "questions": questions},
            timeout=90,
        )
        resp.raise_for_status()
        answers = resp.json()["answers"]
        scores.extend(answers[f"c{j}"]["noul"] for j in range(len(batch)))
    return scores


def score_desklib(texts):
    import torch
    import torch.nn as nn
    from transformers import AutoConfig, AutoModel, AutoTokenizer, PreTrainedModel

    model_id = "desklib/ai-text-detector-v1.01"

    class DesklibAIDetectionModel(PreTrainedModel):
        config_class = AutoConfig

        def __init__(self, config):
            super().__init__(config)
            self.model = AutoModel.from_config(config)
            self.classifier = nn.Linear(config.hidden_size, 1)
            self.init_weights()

        @property
        def all_tied_weights_keys(self):
            # Kompatibilitaets-Fix: der Original-Code der Model Card (2024)
            # crasht beim Laden mit transformers>=5 ("no attribute
            # 'all_tied_weights_keys'"), weil PreTrainedModel diese Property
            # inzwischen intern beim Laden erwartet und unsere Subklasse sie
            # nicht sinnvoll vererbt. Leeres Dict ist korrekt, weil der
            # Classifier-Kopf nichts mit dem Encoder tiedt.
            return {}

        def forward(self, input_ids, attention_mask=None):
            outputs = self.model(input_ids, attention_mask=attention_mask)
            last_hidden_state = outputs[0]
            mask = attention_mask.unsqueeze(-1).expand(last_hidden_state.size()).float()
            summed = torch.sum(last_hidden_state * mask, dim=1)
            counted = torch.clamp(mask.sum(dim=1), min=1e-9)
            pooled = summed / counted
            return self.classifier(pooled)

    tok = AutoTokenizer.from_pretrained(model_id)
    model = DesklibAIDetectionModel.from_pretrained(model_id)
    model.eval()

    scores = []
    batch_size = 8
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            # nur auf den längsten Text im Batch auffüllen - feste 768 Tokens ändern die Scores nicht
            # (Mean-Pooling maskiert), kosten aber ein Vielfaches an Rechenzeit
            enc = tok(batch, padding=True, truncation=True, max_length=768, return_tensors="pt")
            logits = model(input_ids=enc["input_ids"], attention_mask=enc["attention_mask"])
            probs = torch.sigmoid(logits).squeeze(-1)
            scores.extend(probs.tolist())
    return scores


def score_tmr(texts):
    import torch
    from transformers import AutoModelForSequenceClassification, AutoTokenizer

    model_id = "Oxidane/tmr-ai-text-detector"
    tok = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForSequenceClassification.from_pretrained(model_id)
    model.eval()

    scores = []
    batch_size = 16
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            enc = tok(batch, return_tensors="pt", truncation=True, padding=True, max_length=512)
            logits = model(**enc).logits
            probs = torch.softmax(logits, dim=-1)
            # id2label ist modell-spezifisch - beim ersten Lauf ausgeben und pruefen
            ai_index = [k for k, v in model.config.id2label.items() if "ai" in v.lower() or "machine" in v.lower() or "generated" in v.lower()]
            idx = ai_index[0] if ai_index else 1
            scores.extend(probs[:, idx].tolist())
    print(f"(id2label war: {model.config.id2label}, genutzter AI-Index: {idx})")
    return scores


def score_hf(texts, model_id, batch_size=8, max_length=512):
    """Generischer Scorer fuer WP-06-Kandidaten: beliebiges HF-Repo mit
    AutoModelForSequenceClassification. Erkennt selbst, ob das Modell einen
    einzelnen Logit (Sigmoid, wie desklib/gradient) oder mehrere Klassen
    (Softmax + AI-Index aus id2label, wie TMR) ausgibt."""
    import torch
    from transformers import AutoModelForSequenceClassification, AutoTokenizer

    tok = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForSequenceClassification.from_pretrained(model_id)
    model.eval()
    num_labels = model.config.num_labels

    idx = None
    if num_labels != 1:
        id2label = model.config.id2label
        ai_index = [k for k, v in id2label.items() if "ai" in str(v).lower() or "machine" in str(v).lower() or "generated" in str(v).lower()]
        idx = ai_index[0] if ai_index else 1
        print(f"({model_id}: id2label={id2label}, genutzter AI-Index={idx})")
    else:
        print(f"({model_id}: num_labels=1, Sigmoid-Ausgabe)")

    scores = []
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            enc = tok(batch, return_tensors="pt", truncation=True, padding=True, max_length=max_length)
            logits = model(**enc).logits
            if num_labels == 1:
                probs = torch.sigmoid(logits).squeeze(-1)
            else:
                probs = torch.softmax(logits, dim=-1)[:, idx]
            scores.extend(probs.tolist())
    return scores


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--backend", choices=["laya", "tmr", "desklib"], required=True)
    args = parser.parse_args()

    sample = load_sample()
    texts = [t for t, _ in sample]
    labels = [l for _, l in sample]

    if args.backend == "laya":
        scores = score_laya(texts)
    elif args.backend == "desklib":
        scores = score_desklib(texts)
    else:
        scores = score_tmr(texts)

    report(args.backend, labels, scores)


if __name__ == "__main__":
    main()
