"""
Evaluiert ein oder mehrere Backends gegen eval_sample.jsonl (100 balancierte
Beispiele aus dem HC3-Holdout-Split) und druckt Accuracy@0.5 + AUROC.

Nutzung:
    .venv/Scripts/python.exe evaluate_backends.py --backend laya
    .venv/Scripts/python.exe evaluate_backends.py --backend tmr
"""

import argparse
import json

import requests


def load_sample(path="eval_sample.jsonl"):
    rows = [json.loads(l) for l in open(path, encoding="utf-8")]
    return [(r["text"], r["label"]) for r in rows]


def auroc(labels, scores):
    pairs = sorted(zip(scores, labels))
    n_pos = sum(labels)
    n_neg = len(labels) - n_pos
    if n_pos == 0 or n_neg == 0:
        return float("nan")
    rank_sum = 0.0
    i = 0
    n = len(pairs)
    while i < n:
        j = i
        while j < n and pairs[j][0] == pairs[i][0]:
            j += 1
        avg_rank = (i + 1 + j) / 2.0
        for k in range(i, j):
            if pairs[k][1] == 1:
                rank_sum += avg_rank
        i = j
    return (rank_sum - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)


def acc_at(labels, scores, thresh):
    preds = [1 if s >= thresh else 0 for s in scores]
    return sum(p == l for p, l in zip(preds, labels)) / len(labels), preds


def report(name, labels, scores):
    acc50, preds50 = acc_at(labels, scores, 0.5)
    a = auroc(labels, scores)

    best_t, best_acc = 0.5, acc50
    for i in range(1, 100):
        t = i / 100
        acc, _ = acc_at(labels, scores, t)
        if acc > best_acc:
            best_acc, best_t = acc, t

    tp = sum(p == 1 and l == 1 for p, l in zip(preds50, labels))
    fp = sum(p == 1 and l == 0 for p, l in zip(preds50, labels))
    fn = sum(p == 0 and l == 1 for p, l in zip(preds50, labels))
    tn = sum(p == 0 and l == 0 for p, l in zip(preds50, labels))

    _, preds_best = acc_at(labels, scores, best_t)
    tp2 = sum(p == 1 and l == 1 for p, l in zip(preds_best, labels))
    fp2 = sum(p == 1 and l == 0 for p, l in zip(preds_best, labels))
    fn2 = sum(p == 0 and l == 1 for p, l in zip(preds_best, labels))
    tn2 = sum(p == 0 and l == 0 for p, l in zip(preds_best, labels))

    print(f"\n=== {name} ===")
    print(f"Accuracy@0.5: {acc50:.3f}   AUROC: {a:.3f}")
    print(f"Confusion@0.5: TP={tp} FP={fp} FN={fn} TN={tn}")
    print(f"Score-Range: min={min(scores):.3f} max={max(scores):.3f} mean={sum(scores)/len(scores):.3f}")
    print(f"Beste Schwelle auf diesem Sample: {best_t:.2f} -> Accuracy={best_acc:.3f}")
    print(f"Confusion@best: TP={tp2} FP={fp2} FN={fn2} TN={tn2}")

    with open(f"eval_scores_{name}.jsonl", "w", encoding="utf-8") as f:
        for s, l in zip(scores, labels):
            f.write(json.dumps({"score": s, "label": l}) + "\n")


def score_laya(texts, server_url="http://127.0.0.1:11500", model="english"):
    scores = []
    batch_size = 8
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        state = {"candidates": [{"text": t} for t in batch]}
        questions = {
            f"c{j}": {
                "type": "noul",
                "instructions": (
                    f"Is candidates[{j}].text primarily generated by an AI/LLM, rather than "
                    "written by a human? Judge only the writing style/patterns, not the topic or correctness."
                ),
            }
            for j in range(len(batch))
        }
        resp = requests.post(
            f"{server_url}/v1/systemone",
            json={"model": model, "state": state, "questions": questions},
            timeout=90,
        )
        resp.raise_for_status()
        answers = resp.json()["answers"]
        scores.extend(answers[f"c{j}"]["noul"] for j in range(len(batch)))
    return scores


def score_tmr(texts):
    import torch
    from transformers import AutoModelForSequenceClassification, AutoTokenizer

    model_id = "Oxidane/tmr-ai-text-detector"
    tok = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForSequenceClassification.from_pretrained(model_id)
    model.eval()

    scores = []
    batch_size = 16
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            enc = tok(batch, return_tensors="pt", truncation=True, padding=True, max_length=512)
            logits = model(**enc).logits
            probs = torch.softmax(logits, dim=-1)
            # id2label ist modell-spezifisch - beim ersten Lauf ausgeben und pruefen
            ai_index = [k for k, v in model.config.id2label.items() if "ai" in v.lower() or "machine" in v.lower() or "generated" in v.lower()]
            idx = ai_index[0] if ai_index else 1
            scores.extend(probs[:, idx].tolist())
    print(f"(id2label war: {model.config.id2label}, genutzter AI-Index: {idx})")
    return scores


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--backend", choices=["laya", "tmr"], required=True)
    args = parser.parse_args()

    sample = load_sample()
    texts = [t for t, _ in sample]
    labels = [l for _, l in sample]

    if args.backend == "laya":
        scores = score_laya(texts)
    else:
        scores = score_tmr(texts)

    report(args.backend, labels, scores)


if __name__ == "__main__":
    main()
